exclude: [temp.html, Gemfile, Gemfile.lock, README.md, Rakefile, Capfile]
gems: [bourbon, neat]

source:      .
destination: ./_site
plugins:     ./_plugins

paginate: 5
paginate_path: "blog/page:num"

sass:
    sass_dir: _sass

future:      true
lsi:         false
permalink:   /blog/:year/:month/:day/:title/
encoding: 	 UTF-8
highlighter: pygments